# Generated by Django 4.2.23 on 2026-02-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0017_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='mobilenumber',
            field=models.CharField(max_length=15),
        ),
    ]
